name: CI/CD for MFC C++ Project

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Initialize and update submodules

      - name: Set up MSVC
        run: |
          choco install visualstudio2019buildtools --package-parameters "--includeRecommended"
      - name: Build C++ project
        run: msbuild smtp-xoauth2.sln /t:Build
