name: CI/CD for MFC C++ Project

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Initialize and update submodules

      - name: Set up MSVC
        uses: microsoft/setup-msvc@v2
        with:
          msvc-version: 2019

      - name: Build C++ project
        run: msbuild YourProject.sln /t:Build
